#!/bin/sh

WORKING_DIR=$(pwd)
echo "Current working directory: $(pwd)"

echo "Start of ARGUS-SAF analysis for DroidBench"

java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterAppCommunication/Echoer.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterAppCommunication/SendSMS.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterAppCommunication/StartActivityForResult1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ActivityCommunication1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ActivityCommunication2.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ActivityCommunication3.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ActivityCommunication4.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ActivityCommunication5.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ActivityCommunication6.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ActivityCommunication7.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ActivityCommunication8.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/BroadcastTaintAndLeak1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ComponentNotInManifest1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/EventOrdering1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/IntentSink1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/IntentSink2.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/ServiceCommunication1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/SharedPreferences1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/Singletons1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/DroidBench/InterComponentCommunication/UnresolvableIntent1.apk"

echo "End of ARGUS-SAF analysis for DroidBench"


echo "Start of ARGUS-SAF analysis for ICC-Bench"

java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_explicit_nosrc_nosink.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_explicit_nosrc_sink.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_explicit_src_nosink.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_explicit_src_sink.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_implicit_nosrc_nosink.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_implicit_nosrc_sink.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_implicit_src_nosink.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_implicit_src_sink.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_intentservice.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccHandling/icc_stateful.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_dynregister1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_dynregister2.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_explicit1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_implicit_action.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_implicit_category.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_implicit_data1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_implicit_data2.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_implicit_mix1.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/IccTargetFinding/icc_implicit_mix2.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/Mixed/icc_rpc_comprehensive.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/RpcHandling/rpc_localservice.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/RpcHandling/rpc_messengerservice.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/RpcHandling/rpc_remoteservice.apk"
java -jar "$WORKING_DIR/ARGUS-SAF/argus.jar" t -o "$WORKING_DIR/ARGUS-SAF/output" "$WORKING_DIR/ICC-Bench/RpcHandling/rpc_returnsensitive.apk"

echo "End of ARGUS-SAF analysis for ICC-Bench"
